name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15  # Use the latest macOS runner
    
    steps:
    - uses: actions/checkout@v4
    
    - name: List available Xcode versions
      run: |
        echo "Available Xcode versions:"
        ls /Applications/ | grep Xcode
        echo "Currently selected Xcode:"
        xcode-select -p
    
    - name: Use latest available Xcode
      run: |
        # Find the latest Xcode version
        LATEST_XCODE=$(ls /Applications/ | grep "Xcode_" | sort -V | tail -1)
        echo "Using: $LATEST_XCODE"
        sudo xcode-select -s /Applications/$LATEST_XCODE/Contents/Developer
        
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: List schemes
      run: |
        echo "Listing available schemes..."
        xcodebuild -list -project Navigasi.xcodeproj
    
    - name: Build
      run: |
        xcodebuild clean build \
          -project Navigasi.xcodeproj \
          -scheme Navigasi \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
          -configuration Debug
