name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: List schemes
      run: |
        echo "Listing available schemes..."
        xcodebuild -list -json
    
    - name: Build
      run: |
        xcodebuild clean build \
          -project Navigasi.xcodeproj \
          -scheme YourSchemeNameHere \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2'
